version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data    
      
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./config/rsa:/opt/app/config/rsa
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./config/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    depends_on:
      app:
        condition: service_started

volumes:
  db_data: